package GUI;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

/**
 * @author Jorge Hernandez Araya
 */
public class ReturnarGUI extends javax.swing.JPanel {

    public ReturnarGUI() {
        initComponents();
        presentarTableAuto();
    }

    private void presentarTableAuto() {
//        DefaultTableModel modelo = (DefaultTableModel) TableRentados.getModel();
//        TableRentados.setModel(modelo);
//        //TableModel modeloDatos = TableRentados.getModel();
//
//        try {
//            ResultSet rs = ClientSocket.listRentados();
//
//            ResultSetMetaData metaData = rs.getMetaData();
//
//            // Names of columns
//            Vector<String> columnNames = new Vector<String>();
//            int columnCount = (metaData.getColumnCount()) - 1;
//
//            columnNames.add("Placa");
//            columnNames.add("Marca");
//            columnNames.add("Modelo");
//            columnNames.add("Cedula");
//            columnNames.add("Nombre");
//            columnNames.add("Apellido1");
//            columnNames.add("Apellido2");
//            columnNames.add("Correo");
//            columnNames.add("Telefono");
//
//            // Data of the table
//            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
//            while (rs.next()) {
//                Vector<Object> vector = new Vector<Object>();
//                for (int i = 1; i <= columnCount; i++) {
//                    vector.add(rs.getObject(i));
//                }
//                data.add(vector);
//            }
//
//            modelo.setDataVector(data, columnNames);
//            //TableAuto.setEnabled(false);
//
//        } catch (Exception e) {
//
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        Separator1 = new javax.swing.JSeparator();
        btmBPlaca = new javax.swing.JButton();
        btmRetornar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRentados = new javax.swing.JTable();
        txtPlaca = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        btmActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 215, -1, -1));

        Title.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("RETORNAR AUTO");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txt1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(0, 0, 0));
        txt1.setText("Placa");
        add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        Separator1.setForeground(new java.awt.Color(0, 0, 0));
        Separator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(Separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 260, -1));

        btmBPlaca.setBackground(new java.awt.Color(18, 90, 173));
        btmBPlaca.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btmBPlaca.setForeground(new java.awt.Color(255, 255, 255));
        btmBPlaca.setText("BUSCAR");
        btmBPlaca.setBorder(null);
        btmBPlaca.setBorderPainted(false);
        btmBPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBPlacaActionPerformed(evt);
            }
        });
        add(btmBPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 110, 30));

        btmRetornar.setBackground(new java.awt.Color(18, 90, 173));
        btmRetornar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btmRetornar.setForeground(new java.awt.Color(255, 255, 255));
        btmRetornar.setText("RETORNAR");
        btmRetornar.setBorder(null);
        btmRetornar.setBorderPainted(false);
        btmRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRetornarActionPerformed(evt);
            }
        });
        add(btmRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 110, 30));

        TableRentados.setBackground(new java.awt.Color(204, 204, 204));
        TableRentados.setForeground(new java.awt.Color(0, 0, 0));
        TableRentados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Marca", "Modelo", "Cedula", "Nombre", "Apellido1", "Apellido2", "Correo", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableRentados);
        if (TableRentados.getColumnModel().getColumnCount() > 0) {
            TableRentados.getColumnModel().getColumn(0).setResizable(false);
            TableRentados.getColumnModel().getColumn(2).setResizable(false);
            TableRentados.getColumnModel().getColumn(3).setResizable(false);
            TableRentados.getColumnModel().getColumn(4).setResizable(false);
            TableRentados.getColumnModel().getColumn(5).setResizable(false);
            TableRentados.getColumnModel().getColumn(6).setResizable(false);
            TableRentados.getColumnModel().getColumn(8).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 730, 130));

        txtPlaca.setBackground(new java.awt.Color(255, 255, 255));
        txtPlaca.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(102, 102, 102));
        txtPlaca.setText("Ingrese la placa");
        txtPlaca.setBorder(null);
        txtPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPlacaMousePressed(evt);
            }
        });
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 260, 30));

        btncancelar.setBackground(new java.awt.Color(255, 102, 102));
        btncancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("CANCELAR");
        btncancelar.setBorder(null);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 110, 30));

        btmActualizar.setBackground(new java.awt.Color(18, 90, 173));
        btmActualizar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btmActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btmActualizar.setText("ACTUALIZAR");
        btmActualizar.setBorder(null);
        btmActualizar.setBorderPainted(false);
        btmActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmActualizarActionPerformed(evt);
            }
        });
        add(btmActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btmBPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmBPlacaActionPerformed

    private void btmRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRetornarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmRetornarActionPerformed

    private void txtPlacaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlacaMousePressed
        // TODO add your handling code here:
        if ("Ingrese la identificacion".equals(txtPlaca.getText())) {
            txtPlaca.setText("");
        }
    }//GEN-LAST:event_txtPlacaMousePressed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:

        txtPlaca.setText("Ingrese la placa");
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btmActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmActualizarActionPerformed
        // TODO add your handling code here:;
        try {

            presentarTableAuto();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btmActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator1;
    private javax.swing.JTable TableRentados;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JButton btmActualizar;
    private javax.swing.JButton btmBPlaca;
    private javax.swing.JButton btmRetornar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt1;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
